id: I4D971CEC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T14:29:10+00:00'
last_modified: '2022-06-08T01:46:55.500588+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD159521
  title: ༢༠༡༡་ལོའི་སྙན་ངག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    B99A:
      image_group_id: I2PD19011
      title: ''
      total_pages: 322
      order: 1
      base_file: B99A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
