id: P004537
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD159521
  title: ༢༠༡༡་ལོའི་སྙན་ངག
  author: ''
  volumes:
    6598e8277d7344d0a5772a0bf4548898:
      image_group_id: I2PD19011
      title: ''
      volume_number: 1
      total_pages: 322
      base_file: v001.txt
